package gitlet;

import java.io.File;
import static gitlet.Utils.*;


/**
 *  Blobs class: The saved contents of files. Since Gitlet saves many versions of files,
 *  a single file might correspond to multiple blobs: each being tracked in a different commit.
 *  each blob represent a version of a file and has its unique ID generated by the sha1 hash
 */
public class Blobs {
    /** The name of the file, which could be the same as the previous files */
    private String fileName;
    /**
     *  The unique ID of a file, generated by sha1 hash
     *  The ID can be used to compare whether the content of two same name files are the same
     */
    private String contentID;

    public Blobs(String fileName) {
        this.fileName = fileName;
        // guessing the "Hello.txt" file added are from the working directory
        File inFile = join(Repository.CWD, fileName);
        // Read the inFile("Hello.txt") and set the ID to its sha1 value
        this.contentID = sha1(readContentsAsString(inFile));
    }
}
